import { describe as suite, test } from 'node:test';
import assert from 'node:assert/strict';
import { join } from 'node:path';

import {
  parseFrontmatter,
  serializeFrontmatter,
  bannerFor,
  renderMarkdownWithBanner,
  resolveSourceDir,
} from '../src/sync/frontmatter.mjs';

suite('parseFrontmatter', () => {
  test('returns body untouched when there is no frontmatter', () => {
    const { data, body } = parseFrontmatter('# Hello\n');
    assert.deepEqual(data, {});
    assert.equal(body, '# Hello\n');
  });

  test('returns body untouched when frontmatter is unterminated', () => {
    const source = '---\nname: x\nno closing delimiter';
    assert.deepEqual(parseFrontmatter(source).data, {});
  });

  test('parses scalars, booleans, numbers, and quoted strings', () => {
    const source = [
      '---',
      'name: spec-reader',
      'readonly: true',
      'disabled: false',
      'nothing: null',
      'count: 42',
      'negative: -7',
      'quoted: "a: b"',
      "single: 'c # d'",
      '# a comment line',
      '---',
      'Body text.',
    ].join('\n');
    const { data, body } = parseFrontmatter(source);
    assert.deepEqual(data, {
      name: 'spec-reader',
      readonly: true,
      disabled: false,
      nothing: null,
      count: 42,
      negative: -7,
      quoted: 'a: b',
      single: 'c # d',
    });
    assert.equal(body, 'Body text.');
  });

  test('parses lists', () => {
    const source = '---\ntools:\n  - Read\n  - Grep\n---\nbody';
    assert.deepEqual(parseFrontmatter(source).data.tools, ['Read', 'Grep']);
  });
});

suite('serializeFrontmatter', () => {
  test('returns the body alone for empty data', () => {
    assert.equal(serializeFrontmatter({}, 'body'), 'body');
  });

  test('round-trips through parseFrontmatter', () => {
    const data = {
      name: 'implementer',
      description: 'Builds features: task by task',
      readonly: false,
      tools: ['Read', 'Write'],
    };
    const out = serializeFrontmatter(data, 'The body.\n');
    assert.deepEqual(parseFrontmatter(out).data, data);
    assert.equal(parseFrontmatter(out).body, 'The body.\n');
  });

  test('quotes scalars containing yaml-significant characters', () => {
    const out = serializeFrontmatter({ description: 'a: b' }, '');
    assert.ok(out.includes('description: "a: b"'));
  });

  test('serializes lists of plain objects (copilot handoffs shape)', () => {
    const data = { handoffs: [{ label: 'Continue', agent: 'beta', send: false }] };
    const out = serializeFrontmatter(data, '');
    assert.ok(out.includes('  - label: Continue'));
    assert.ok(out.includes('    agent: beta'));
    assert.ok(out.includes('    send: false'));
  });

  test('serializes empty lists inline', () => {
    assert.ok(serializeFrontmatter({ tools: [] }, '').includes('tools: []'));
  });
});

suite('bannerFor', () => {
  test('fills in the source for known kinds and returns empty for unknown', () => {
    assert.equal(
      bannerFor('markdown', 'agents/x.md'),
      '<!-- GENERATED BY `harness sync` — edit harness/agents/x.md instead. -->',
    );
    assert.ok(bannerFor('json', 'harness.config.json').startsWith('//'));
    assert.equal(bannerFor('toml', 'x'), '');
  });
});

suite('renderMarkdownWithBanner', () => {
  test('keeps frontmatter first and injects the banner at the top of the body', () => {
    const out = renderMarkdownWithBanner({
      data: { name: 'x' },
      body: '\n\n# Title\n',
      source: 'agents/x.md',
    });
    assert.ok(out.startsWith('---\n'));
    const { data, body } = parseFrontmatter(out);
    assert.equal(data.name, 'x');
    assert.ok(body.startsWith('<!-- GENERATED'));
    assert.ok(body.includes('# Title'));
  });
});

suite('resolveSourceDir', () => {
  const harnessRoot = '/repo/harness';
  test('falls back to the conventional dir', () => {
    assert.equal(resolveSourceDir(harnessRoot, undefined, 'agents'), join(harnessRoot, 'agents'));
  });
  test('resolves harness/-prefixed paths from the repo root', () => {
    assert.equal(resolveSourceDir(harnessRoot, 'harness/custom', 'agents'), '/repo/harness/custom');
  });
  test('resolves other paths from the harness root', () => {
    assert.equal(resolveSourceDir(harnessRoot, 'elsewhere/agents', 'agents'), '/repo/harness/elsewhere/agents');
  });
});
