// Tiny YAML-frontmatter parser/serializer. Intentionally minimal: it supports
// the shapes used in agent/command/skill files (string keys, string or list
// values). External YAML deps are avoided so the harness has zero runtime
// dependencies.

import { readFileSync, readdirSync, statSync, unlinkSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';

// Resolve a content directory from config (paths.agents, paths.commands,
// paths.skills, paths.hooks, ...). Configured paths are relative to the
// repo root when they start with "harness/", otherwise relative to the
// harness root. Falls back to the conventional directory under harness/.
export function resolveSourceDir(harnessRoot, configured, fallback) {
  if (!configured) return join(harnessRoot, fallback);
  if (configured.startsWith('harness/')) {
    return resolve(harnessRoot, '..', configured);
  }
  return resolve(harnessRoot, configured);
}

const GENERATED_MARKER = 'GENERATED BY `harness sync`';

const FRONTMATTER_DELIMITER = '---';

export function parseFrontmatter(source) {
  if (!source.startsWith(`${FRONTMATTER_DELIMITER}\n`)) {
    return { data: {}, body: source };
  }
  const end = source.indexOf(`\n${FRONTMATTER_DELIMITER}`, FRONTMATTER_DELIMITER.length + 1);
  if (end === -1) return { data: {}, body: source };

  const yamlBlock = source.slice(FRONTMATTER_DELIMITER.length + 1, end);
  const bodyStart = end + FRONTMATTER_DELIMITER.length + 1;
  // Strip all leading blank lines so parse(serialize(data, body)) returns
  // the body unchanged (serialize inserts one blank line after `---`).
  const body = source.slice(bodyStart).replace(/^\n+/, '');
  return { data: parseYamlBlock(yamlBlock), body };
}

export function serializeFrontmatter(data, body) {
  const keys = Object.keys(data);
  if (keys.length === 0) return body;
  const lines = [FRONTMATTER_DELIMITER];
  for (const key of keys) {
    lines.push(serializeYamlEntry(key, data[key]));
  }
  lines.push(FRONTMATTER_DELIMITER, '');
  return `${lines.join('\n')}\n${body}`;
}

function parseYamlBlock(block) {
  const data = {};
  const lines = block.split('\n');
  let currentKey = null;
  let currentList = null;

  for (const rawLine of lines) {
    if (!rawLine.trim() || rawLine.trim().startsWith('#')) continue;

    const listMatch = rawLine.match(/^\s+-\s*(.*)$/);
    if (listMatch && currentList) {
      currentList.push(unquote(listMatch[1].trim()));
      continue;
    }

    const keyMatch = rawLine.match(/^([A-Za-z0-9_.-]+)\s*:\s*(.*)$/);
    if (!keyMatch) continue;
    const [, key, rest] = keyMatch;
    currentKey = key;
    const value = rest.trim();
    if (value === '') {
      currentList = [];
      data[key] = currentList;
    } else {
      currentList = null;
      data[key] = unquote(value);
    }
  }

  return data;
}

function unquote(value) {
  if (value === 'true') return true;
  if (value === 'false') return false;
  if (value === 'null') return null;
  if (/^-?\d+$/.test(value)) return Number(value);
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }
  return value;
}

// Serializes a single top-level YAML entry. Supports scalars, lists of
// scalars, and lists of plain objects whose values are scalars (used for
// Copilot handoffs). Deeper nesting is intentionally unsupported; if a
// future target needs it, extend `serializeListItem`.
function serializeYamlEntry(key, value) {
  if (Array.isArray(value)) {
    if (value.length === 0) return `${key}: []`;
    return [`${key}:`, ...value.map((item) => serializeListItem(item))].join('\n');
  }
  return `${key}: ${formatScalar(value)}`;
}

function serializeListItem(item) {
  if (!isPlainObject(item)) {
    return `  - ${formatScalar(item)}`;
  }
  const childKeys = Object.keys(item);
  if (childKeys.length === 0) return '  - {}';
  const lines = [];
  for (let i = 0; i < childKeys.length; i += 1) {
    const childKey = childKeys[i];
    const childValue = item[childKey];
    const prefix = i === 0 ? '  - ' : '    ';
    lines.push(`${prefix}${childKey}: ${formatScalar(childValue)}`);
  }
  return lines.join('\n');
}

function isPlainObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function formatScalar(value) {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'boolean' || typeof value === 'number') return String(value);
  const str = String(value);
  if (/[:#\n"']/.test(str)) {
    return JSON.stringify(str);
  }
  return str;
}

export function readMarkdownDir(dir) {
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return [];
  }
  return entries
    .filter((name) => name.endsWith('.md'))
    .map((name) => {
      const path = join(dir, name);
      const source = readFileSync(path, 'utf8');
      const { data, body } = parseFrontmatter(source);
      return { name, path, source, data, body };
    });
}

// Removes files in `dir` that were previously written by `harness sync`
// (identified by the GENERATED banner). User-authored files are left
// untouched. Useful for cleaning up legacy output paths after the sync
// implementation changes.
export function pruneGeneratedFiles(dir, { extensions } = {}) {
  if (!existsSync(dir)) return [];
  const removed = [];
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return removed;
  }
  for (const name of entries) {
    const path = join(dir, name);
    let stat;
    try {
      stat = statSync(path);
    } catch {
      continue;
    }
    if (!stat.isFile()) continue;
    if (extensions && !extensions.some((ext) => name.endsWith(ext))) continue;
    let contents;
    try {
      contents = readFileSync(path, 'utf8');
    } catch {
      continue;
    }
    if (!contents.includes(GENERATED_MARKER)) continue;
    try {
      unlinkSync(path);
      removed.push(name);
    } catch {
      // Best-effort; ignore failures.
    }
  }
  return removed;
}

export function listDirectories(dir) {
  try {
    return readdirSync(dir)
      .filter((name) => {
        const path = join(dir, name);
        try {
          return statSync(path).isDirectory();
        } catch {
          return false;
        }
      });
  } catch {
    return [];
  }
}

export const GENERATED_BANNERS = Object.freeze({
  markdown: '<!-- GENERATED BY `harness sync` — edit harness/{source} instead. -->',
  json: '// GENERATED BY `harness sync` — edit harness/{source} instead.',
  jsonc: '// GENERATED BY `harness sync` — edit harness/{source} instead.',
});

export function bannerFor(kind, source) {
  const template = GENERATED_BANNERS[kind];
  if (!template) return '';
  return template.replace('{source}', source);
}

// Render a markdown file with frontmatter intact and a "do not edit" banner
// placed as the first line of the body. Placing the banner before the
// frontmatter would break parsers that require `---` on line 1.
export function renderMarkdownWithBanner({ data, body, source }) {
  const banner = bannerFor('markdown', source);
  const trimmedBody = body.replace(/^\n+/, '');
  const bodyWithBanner = `${banner}\n\n${trimmedBody}`;
  return serializeFrontmatter(data ?? {}, bodyWithBanner);
}
